config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'users#index'


  resources :recipes, only: %i[index show new create destroy] do
    resources :recipe_foods, only: %i[new create destroy]
  end
  resources :foods, only: %i[index new create destroy]
  resources :public_recipes, only: [:index]
  resources :general_shopping_lists, only: [:index]

  resources :recipes do
    member do
      patch :toggle_public
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods

  validates :name, :measurement_unit, :price, :quantity, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods

  validates :name, :preparation_time, :cooking_time, :description, :user_id, presence: true
  validates :preparation_time, :cooking_time, numericality: { only_integer: true }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :foods, foreign_key: :user_id
  has_many :recipes, foreign_key: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @user = current_user
    @foods = @user.foods.all
  end

  def new
    @user = current_user
    @food = Food.new
  end

  def create
    @user = current_user
    @food = current_user.foods.build(food_params)
    respond_to do |format|
      format.html do
        if @food.save
          redirect_to foods_path, notice: 'food was successfully added.'
        else
          render :new
          flash.now[:alert] = 'food could not be added. Please try again.'
        end
      end
    end
  end

  def destroy
    @user = current_user
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path, notice: 'food was successfully deleted.'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/general_shopping_lists_controller.rb
class GeneralShoppingListsController < ApplicationController
  def index
    @user = current_user
    @recipe = Recipe.includes(:recipe_foods).find(params[:recipe_id])
    @user_foods_ids = @user.foods.pluck(:id)
    @recipe_foods_ids = @recipe.recipe_foods.pluck(:food_id)
    @missing_foods = @recipe_foods_ids - @user_foods_ids
    @missing_food_records = Food.where(id: @missing_foods)
    @recipe_foods = @recipe.recipe_foods

    @food_prices = {}
    @sum = 0
    @missing_food_records.each do |food|
      recipe_food = @recipe.recipe_foods.find_by(food_id: food.id)
      if recipe_food
        @food_prices[food.id] = food.price * recipe_food.quantity.to_i
        @sum += @food_prices[food.id]
      else
        @food_prices[food.id] = 0
      end
    end
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where(public: true).includes(:user, :recipe_foods)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @user = current_user
    @foods = Food.all
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    @user = current_user
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.build(ref_params.merge(recipe_id: @recipe.id))
    respond_to do |format|
      format.html do
        if @recipe_food.save
          redirect_to recipe_path(@recipe), notice: 'ingredient was successfully added.'
        else
          render :new
          flash.now[:alert] = 'Ingredient could not be added. Please try again.'
        end
      end
    end
  end

  def destroy
    @user = current_user
    @recipe_food = RecipeFood.find(params[:recipe_id])
    @recipe = @recipe_food.recipe

    if @recipe_food.destroy
      redirect_to recipe_path(@recipe), notice: 'Food was successfully deleted from the recipe.'
    else
      redirect_to recipe_path(@recipe), alert: 'Failed to delete food from the recipe.'
    end
  end

  private

  def ref_params
    params.require(:recipe_food).permit(:quantity, :food_id, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @user = current_user
    @recipes = @user.recipes.all
  end

  def show
    @user = current_user
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
    @recipe_foods = @recipe.recipe_foods
  end

  def new
    @user = current_user
    @recipe = Recipe.new
  end

  def create
    @user = current_user
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      format.html do
        if @recipe.save
          redirect_to recipes_path, notice: 'Recipe created successfully.'
        else
          render :new
          flash.now[:alert] = 'recipe could not be added. Please try again.'
        end
      end
    end
  end

  def destroy
    @user = current_user
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe deleted successfully.'
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    return unless @recipe.user == current_user

    @recipe.update_column(:public, !@recipe.public)
    redirect_to @recipe, notice: 'Recipe status updated.'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def calculate_total_price(recipe)
    total_price = 0.0

    recipe.recipe_foods.each do |recipe_food|
      total_price += recipe_food.food.price.to_f
    end

    total_price
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shopping_list_helper.rb
module GeneralShoppingListHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_food_helper.rb
module RecipeFoodHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<%# <%= stylesheet_link_tag 'foods', media: 'all', 'data-turbolinks-track': 'reload' %>
<tr class = 'table-raw'>
<td class = 'table-data'><%=food.name%></td>
<td class = 'table-data'><%=food.measurement_unit%></td>
<td class = 'table-data'>$<%=food.price%></td>
<td class = 'table-data'><%=food.quantity%></td>
<td class = 'table-data'>
<%= link_to "DELETE", food_path(food),
  class: "btn-delete" ,
  method: :delete, data: {
                    turbo_method: :delete,
                      turbo_confirm: "Are you sure?"} %>
</td>
</tr>

app/views/foods/index.html.erb
<%= stylesheet_link_tag 'foods', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class='no-foods'>
<%= "there are No foods right now.you can add a food." if @foods.empty?%>
</div>
<div class='add-food'>
<%= link_to "Add food", new_food_path, class: "btn btn-addfood" %>
</div>
<table class = 'food-table'>
<tr class = 'table-raw'>
<th class = 'table-data'>name</th>
<th class = 'table-data'>measurement_unit</th>
<th class = 'table-data'>Price</th>
<th class = 'table-data'>quantity</th>
<th></th>

</tr>
<% @foods.includes(:user).each do |food| %>
<%= render food %>
<%end%>
</table>

app/views/foods/new.html.erb
<div class="form-container">
<h1>Add a new food</h1>
<%= form_with model: @food, url: foods_path, method: :post, local: true, scope: :food do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>
  <div class="field">
    <%= form.label :measurement_unit %>
    <%= form.select :measurement_unit, options_for_select(['grams','units','leters']), required: true %>
  </div>
  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price,type: "number", step: "0.001", required: true %>
  </div>
  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, required: true, min: 1 %>
  </div>
  <div class="actions">
   <%= form.submit "Create food" %>
  </div>
<% end %>
</div>

app/views/general_shopping_list/index.html.erb
<h1>GeneralShoppingList#index</h1>
<p>Find me in app/views/general_shopping_list/index.html.erb</p>

app/views/general_shopping_lists/index.html.erb
<%= stylesheet_link_tag 'foods', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'recipe_details', media: 'all', 'data-turbolinks-track': 'reload' %>
<h1>Shopping List</h1>

<div class= 'amount-price'>
  <p>Amount of food items to buy : <%= @missing_foods.count %> <p>
  <p>total value of food needed: <%= @sum %></p>
</div>

<section class='shopping-table'>
<table class='table food-table shopping-t'>
    <tr>
      <th class='table-data'>Food</th>
      <th class='table-data'>Quantity</th>
      <th class='table-data'>Price</th>
    </tr>
    <% @missing_food_records.each do |food| %>
      <tr>
        <td class='table-data'><%= food.name %></td>
        <td class='table-data'><%= "#{food.quantity} #{food.measurement_unit}" %></td>
        <td class='table-data'><%= "$#{@food_prices[food.id]}" %></td>
      </tr>
    <% end %>
  </table>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>

      <div class="container">
      <% if user_signed_in? %>
      <ul>
        <li class="dropdown">
          <a class="btn dropbtn">Menu </a>
          <div class="dropdown-content">
            <%= link_to 'foods', foods_path , class: " pages-links btn-foods" %>
            <%= link_to 'your recipes', recipes_path, class: "pages-links btn-recipes"%>
            <%= link_to 'public recipes', public_recipes_path, class: "pages-links btn-recipes"%>
          </div>
        </li>
      </ul>
      <% end %>  
      <div class="sign-in">
          <% if user_signed_in? %>
            <div class="text-end">
              <%= link_to 'Logout', destroy_user_session_path, class: "btn btn-logout", data: { turbo_method: :delete } %>
            </div>
          <% else %>
            <div class="sign-up">
              <%= link_to 'Login', new_user_session_path, class: "btn btn-login" %>
              <%= link_to 'Sign-up', new_user_registration_path, class: "btn btn-sign-up" %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </main>
  </body>
</html>

app/views/public_recipes/index.html.erb
<h1>Public Recipes List</h1>

<% @public_recipes.each do |recipe| %>
    <ul class="recipe-list">
        <li>
            <div class="left">
              <h2><p><%= link_to recipe.name, recipe, class: "recipe-link" %></p><br></2>
              <p>By: <%= recipe.user.name %></p>
            </div>
            <div class="right">
               <p>Total food items: <%= recipe.recipe_foods.count %></p>
               <p>Total price: <%= calculate_total_price(recipe) %></p>
            </div>
       </li>
    </ul>
<% end %>

app/views/recipe/index.html.erb
<h1>Recipe#index</h1>
<p>Find me in app/views/recipe/index.html.erb</p>

app/views/recipe_food/index.html.erb
<h1>RecipeFood#index</h1>
<p>Find me in app/views/recipe_food/index.html.erb</p>

app/views/recipe_foods/new.html.erb
<div class="form-container">
  <h1>Add a new food</h1>
  <%= form_with model: @recipe_food, url: recipe_recipe_foods_path(@recipe), method: :post, local: true, scope: :recipe_food do |form| %>
  
    <div class="field">
      <%= form.label :food_id %>
      <%= form.collection_select(:food_id, @foods, :id, :name, prompt: "Select a food", required: true) %>
    </div>

    <div class="field">
      <%= form.label :quantity %>
      <%= form.number_field :quantity, required: true, min: 1 %>
    </div>

    <div class="actions">
      <%= form.submit "Create food" %>
    </div>
  <% end %>
</div>

app/views/recipes/index.html.erb
<h1>Your Recipes</h1>

<% if @recipes.any? %>
<ul class="recipe-list">
    <%= link_to "Create a new recipe", new_recipe_path, class: "btn-create btn-recipe" %>
    <% @recipes.each do |recipe| %>
        <li>
            <div class="left">
                <p><%= link_to recipe.name, recipe, class: "recipe-link" %></p><br>
                <%= link_to "Remove", recipe_path(recipe), class: "remove-btn", method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this recipe?" } %>
            </div>
            <div class="right">
              <p><%= recipe.description %></p>
            </div>
         </li>
    <% end %>
</ul>
<% else %>
  <p class="new-recipe">You don't have any recipes yet. <%= link_to "Create a new recipe", new_recipe_path, class: "btn-create" %></p> 
<% end %>

app/views/recipes/new.html.erb
<div class='form-container'>
<h1>Create a New Recipe</h1>

<%= form_with model: @recipe, url: recipes_path, method: :post, local: true, scope: :recipe do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :preparation_time %>
    <%= form.number_field :preparation_time, step: 1, min: 1 %>
  </div>

  <div class="field">
    <%= form.label :cooking_time %>
    <%= form.number_field :cooking_time, step: 1, min: 1 %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field checkbox">
    <%= form.label :public %>
    <%= form.check_box :public %>
  </div>

  <div class="actions">
    <%= form.submit "Create Recipe" %>
  </div>
<% end %>
   <div class="back-to-recipe">
      <%= link_to "Back to My Recipes", recipes_path %>
   </div>
</div>

app/views/recipes/show.html.erb
<%= stylesheet_link_tag 'foods', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'recipe_details', media: 'all', 'data-turbolinks-track': 'reload' %>

<h1><%= @recipe.name %></h1>
<section class='recipe-details'>
<div>
<p>preparation time:<%=@recipe.preparation_time%></p>
<p>cooking time:<%=@recipe.cooking_time%> </p>
<p><%=@recipe.description%><p>
</div>
<div class='status'>
<p>Status: <%= @recipe.public ? 'Public' : 'Private' %></p>

<%= form_for @recipe, url: toggle_public_recipe_path(@recipe), method: :patch do |f| %>
  <%= f.hidden_field :public, value: !@recipe.public %>
  <button type="submit" class="toggle-status-button" style="background-image: url('<%= asset_path(@recipe.public ? 'on-button.png' : 'off-button.png') %>');"></button>
<% end %>
<div>

</section>

<section class= 'link-buttons'>
<%=link_to 'Generate Shopping list', general_shopping_lists_path(recipe_id: @recipe.id) , class: 'btn'%>
<%if @recipe.user == current_user%>
<%=link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe), class: 'btn'%>
<%end%>
</section>

<section class= 'recipe-table-section'>
<%if @recipe_foods.empty?%>
        <div class='recipe-show-none'>
            <h1>No Ingredient added. Please add an Ingredient</h1>
        </div>
    <%else%>
      <div class='recipe-show-table'>
        <table class='table recipe-table'>
          <tr>
            <th class='table-data'> Food </th>
            <th class='table-data'> Quantity </th>
            <th class='table-data'> Value </th>
            <% if @recipe.user == current_user%>
               <th class='table-data'> Actions </th>
            <%end%>
            
          </tr>
          <% @recipe_foods.each do |recipe_food| %>
            <tr >
                <td class='table-data'><%=recipe_food.food.name%></td>
                <td class='table-data'><%= "#{recipe_food.quantity}#{recipe_food.food.measurement_unit}"%></td>
                <td class='table-data'><%= "$#{recipe_food.food.price.to_i * recipe_food.quantity.to_i}"%></td>
                <% if @recipe.user == current_user %>
                    <td class='table-data'> 
                      <%= button_to "Delete", recipe_recipe_food_path(recipe_food.id), :method => :delete  %>
                    </td class='table-data'>
                 <%end%>
            </tr>
          <%end%>
        </table>
    <%end%>
</section>

app/views/users/index.html.erb
<div class="welcome-container">
  <h1>Welcome to Our Recipe App!</h1>
  <p>Discover and share delicious recipes with our community of food enthusiasts.</p>
  <%= link_to "Create a New Recipe", new_recipe_path, class: "btn-explore" %>
  <%= link_to "Explore Public Recipes", public_recipes_path, class: "btn-explore" %>
</div>